
main_file: "mf104m-pd-midi.pd"

midi_controllers:
 enable_tap:
  midi_cc: 66
  value: 'ON'
  labels: ['OFF', 'ON']
 delay_speed:
  midi_cc: 2
  value: 'x1'
  labels: ['/4', '/3', '/2', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x8', 'x12']
 filter_dark:
  midi_cc: 68
  value: 'ON'
  labels: ['OFF', 'ON']
 toggle_delay:
  midi_cc: 67
  value: 'ON'
  labels: ['OFF', 'ON']
 mf_midi_channel:
  midi_cc: 69
  value: 1
  value_min: 1
  value_max: 16
